# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      actions-all-dependencies:
        patterns:
          - "*"

  # Maintain Ruby dependencies
  - package-ecosystem: "bundler"
    directories:
      - "/"
      - "/infra"
      - "/support/forms-cli"
      - "/support/pipeline-visualiser"
      - "/support/paused-pipeline-detector"
      - "/infra/deployments/forms/pipelines/pipeline-invoker"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      ruby-all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: "/infra/shared"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      terraform-all-dependencies:
        patterns:
          - "*"
    target-branch: main
