# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk-codepipeline", "~> 1.116"
gem "aws-sdk-sns", "~> 1.116"

group :development, :test do
  gem "rexml", "~> 3.4"
  gem "rspec", "~> 3.13"
  gem "rubocop-govuk", "~> 5.2"
end
