# Burn rate alarms for SLO monitoring
# These monitor the burn rate metrics automatically generated by the SLOs in slos.tf

# All SLO names for burn rate alarm creation
locals {
  # Use the 28-day rolling interval defined in slos.tf
  slo_interval_days    = local.common_goal_config.interval.rolling_interval.duration
  slo_interval_minutes = local.slo_interval_days * 24 * 60

  all_slo_names = concat(
    [for k, v in local.availability_slos : v.name],
    [for k, v in local.latency_slos : v.name],
    [for k, v in local.submission_delivery_slos : v.name]
  )

  # Burn rate alarm configurations; thresholds computed inline per alarm
  # Note: both alarms in a composite pair, the threshold should be calculated
  # using the longer look-back window of that pair — not each alarm's own window.
  burn_rate_configs = {
    fast_1hour = {
      window_minutes           = 60
      threshold_window_minutes = 60
      budget_percent           = 2
    }
    fast_5min = {
      window_minutes           = 5
      threshold_window_minutes = 60 # Uses the longer look-back window of the pair (1 hour)
      budget_percent           = 2
    }
    medium_6hour = {
      window_minutes           = 360
      threshold_window_minutes = 360
      budget_percent           = 5
    }
    medium_30min = {
      window_minutes           = 30
      threshold_window_minutes = 360 # Uses the longer look-back window of the pair (6 hours)
      budget_percent           = 5
    }
    slow_3day = {
      window_minutes           = 4320
      threshold_window_minutes = 4320
      budget_percent           = 10
    }
    slow_6hour = {
      window_minutes           = 360
      threshold_window_minutes = 4320 # Uses the longer look-back window of the pair (3 days)
      budget_percent           = 10
    }
  }
}

# Individual burn rate alarms
# These are used by the composite alarms but don't send notifications directly
resource "aws_cloudwatch_metric_alarm" "slo_burn_rate_alarms" {
  #checkov:skip=CKV2_FORMS_AWS_1:Individual burn rate alarms are used by composite alarms only, no direct alarm actions needed
  for_each = {
    for pair in setproduct(local.all_slo_names, keys(local.burn_rate_configs)) :
    "${pair[0]}-${pair[1]}" => {
      slo_name   = pair[0]
      config_key = pair[1]
      config     = local.burn_rate_configs[pair[1]]
    }
  }

  alarm_name          = "slo-burn-rate-${each.value.slo_name}-${replace(each.value.config_key, "_", "-")}"
  alarm_description   = "Burn rate alarm for ${each.value.slo_name} with ${each.value.config.window_minutes} minute window"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "BurnRate"
  namespace           = "AWS/AppSignals"
  period              = 60
  statistic           = "Average"
  # Burn rate threshold = X% * SLO interval length / look-back window size
  # For both alarms in a composite pair, we use the longer look-back window of that pair per AWS guidelines
  threshold          = (each.value.config.budget_percent / 100.0) * local.slo_interval_minutes / each.value.config.threshold_window_minutes
  treat_missing_data = "notBreaching"

  # These individual alarms don't send notifications directly - they are used by composite alarms
  alarm_actions = []

  dimensions = {
    SloName               = each.value.slo_name
    BurnRateWindowMinutes = tostring(each.value.config.window_minutes)
  }

  tags = {
    Environment  = var.environment_name
    SLO          = each.value.slo_name
    BurnRateType = each.value.config_key
  }
}

# Composite alarms that combine burn rate alarms for alerting
# These follow the multi-window burn rate alerting pattern from the original bash script

# Fast burn rate detection composite alarms
resource "aws_cloudwatch_composite_alarm" "slo_burn_rate_fast_alarms" {
  for_each = {
    for slo_name in local.all_slo_names : slo_name => {
      alarm_name = "slo-burn-rate-${slo_name}-fast"
      slo_name   = slo_name
    }
  }

  alarm_name        = each.value.alarm_name
  alarm_description = <<EOF
    Fast burn rate detection for ${each.value.slo_name} (1-hour and 5-minute windows)

    NEXT STEP: Begin incident process immediately.
EOF
  alarm_rule        = "ALARM(slo-burn-rate-${each.value.slo_name}-fast-1hour) AND ALARM(slo-burn-rate-${each.value.slo_name}-fast-5min)"
  alarm_actions     = [module.alerts.alert_severity.eu_west_2.high]
  actions_enabled   = true
  depends_on        = [aws_cloudwatch_metric_alarm.slo_burn_rate_alarms]

  tags = {
    Environment = var.environment_name
    SLO         = each.value.slo_name
    AlertType   = "fast"
  }
}

# Medium burn rate detection composite alarms
resource "aws_cloudwatch_composite_alarm" "slo_burn_rate_medium_alarms" {
  for_each = {
    for slo_name in local.all_slo_names : slo_name => {
      alarm_name = "slo-burn-rate-${slo_name}-medium"
      slo_name   = slo_name
    }
  }

  alarm_name        = each.value.alarm_name
  alarm_description = <<EOF
    Medium burn rate detection for ${each.value.slo_name} (6-hour and 30-minute windows)

    NEXT STEP: Begin incident process upon picking up ticket.
EOF
  alarm_rule        = "ALARM(slo-burn-rate-${each.value.slo_name}-medium-6hour) AND ALARM(slo-burn-rate-${each.value.slo_name}-medium-30min)"
  alarm_actions     = [module.alerts.alert_severity.eu_west_2.info]
  actions_enabled   = true
  depends_on        = [aws_cloudwatch_metric_alarm.slo_burn_rate_alarms]

  tags = {
    Environment = var.environment_name
    SLO         = each.value.slo_name
    AlertType   = "medium"
  }
}

# Slow burn rate detection composite alarms
resource "aws_cloudwatch_composite_alarm" "slo_burn_rate_slow_alarms" {
  for_each = {
    for slo_name in local.all_slo_names : slo_name => {
      alarm_name = "slo-burn-rate-${slo_name}-slow"
      slo_name   = slo_name
    }
  }

  alarm_name        = each.value.alarm_name
  alarm_description = <<EOF
    Slow burn rate detection for ${each.value.slo_name} (3-day and 6-hour windows)"

    NEXT STEP: Investigate as support ticket or create Trello card to investigate during next sprint.
 EOF
  alarm_rule        = "ALARM(slo-burn-rate-${each.value.slo_name}-slow-3day) AND ALARM(slo-burn-rate-${each.value.slo_name}-slow-6hour)"
  alarm_actions     = [module.alerts.alert_severity.eu_west_2.info]
  actions_enabled   = true
  depends_on        = [aws_cloudwatch_metric_alarm.slo_burn_rate_alarms]

  tags = {
    Environment = var.environment_name
    SLO         = each.value.slo_name
    AlertType   = "slow"
  }
}
