---
roles:
  - role: arn:aws:iam::711966560482:role/codepipeline-readonly
    gds_cli_role: forms-deploy-support
  - role: arn:aws:iam::498160065950:role/codepipeline-readonly
    gds_cli_role: forms-dev-support
  - role: arn:aws:iam::443944947292:role/codepipeline-readonly
    gds_cli_role: forms-prod-support
  - role: arn:aws:iam::972536609845:role/codepipeline-readonly
    gds_cli_role: forms-staging-support

groups:
  "Apply Terraform":
    - "apply-forms-terraform-staging"
    - "apply-forms-terraform-production"
    - "apply-forms-terraform-dev"

  "Product pages":
    - "forms-product-page-image-builder"
    - "deploy-forms-product-page-container-staging"
    - "deploy-forms-product-page-container-production"
    - "deploy-forms-product-page-container-dev"

  "Admin":
    - "forms-admin-image-builder"
    - "deploy-forms-admin-container-staging"
    - "deploy-forms-admin-container-production"
    - "deploy-forms-admin-container-dev"

  "Runner":
    - "forms-runner-image-builder"
    - "deploy-forms-runner-container-staging"
    - "deploy-forms-runner-container-production"
    - "deploy-forms-runner-container-dev"

  "Pipeline visualiser":
    - "deploy-pipeline-visualiser"

  "End to end tests":
    - "e2e-image"
