name: "Test Forms Cli"
on:
  push:
    branches: [forms_cli]
    paths:
      - "support/forms-cli/**"
      - ".github/workflows/forms-cli.yml"
  pull_request:
    branches: [main]
    paths:
      - "support/forms-cli/**"
  merge_group:
    types: [checks_requested]
jobs:
  build_and_test:
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: support/forms-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Determine Ruby version
        id: determine-ruby-version
        run: |
          echo "RUBY_VERSION=$(cat ../../.ruby-version)" >> "$GITHUB_OUTPUT"
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
        with:
          bundler-cache: true
          ruby-version: ${{steps.determine-ruby-version.outputs.RUBY_VERSION}}
          working-directory: support/forms-cli
      - name: Run forms CLI tests
        run: bundle exec rspec
