name: "Pipeline Visualiser checks"
on:
  pull_request:
    branches: [main]
    paths:
      - "support/pipeline-visualiser/**"
      - ".github/workflows/pipeline-visualiser.yml"
  merge_group:
    types: [checks_requested]
jobs:
  build_container:
    runs-on: ubuntu-24.04-arm # The container will ultimately be built for arm64 and run on arm64, so we should test it on arm64.
    name: "Build container"
    defaults:
      run:
        working-directory: support/pipeline-visualiser
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run docker build
        run: docker build .

  run_tests:
    runs-on: ubuntu-24.04-arm
    name: "Build and test"
    defaults:
      run:
        working-directory: support/pipeline-visualiser
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Determine Ruby version
        id: determine-ruby-version
        run: |
          echo "RUBY_VERSION=$(cat ../../.ruby-version)" >> "$GITHUB_OUTPUT"
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true
          ruby-version: ${{steps.determine-ruby-version.outputs.RUBY_VERSION}}
          working-directory: support/pipeline-visualiser
      - name: Run pipeline visualiser tests
        run: bundle exec rspec
