name: "Pipeline Visualiser checks"
on:
  pull_request:
    branches: [main]
    paths:
      - "support/pipeline-visualiser/**"
      - ".github/workflows/pipeline-visualiser.yml"
  merge_group:
    types: [checks_requested]
jobs:
  build_container:
    runs-on: ubuntu-24.04-arm # The container will ultimately be built for arm64 and run on arm64, so we should test it on arm64.
    name: "Build container"
    defaults:
      run:
        working-directory: support/pipeline-visualiser
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run docker build
        run: docker build .

  run_tests:
    runs-on: ubuntu-24.04-arm
    name: "Build and test"
    defaults:
      run:
        working-directory: support/pipeline-visualiser
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Determine Ruby version
        id: determine-ruby-version
        run: |
          echo "RUBY_VERSION=$(cat ../../.ruby-version)" >> "$GITHUB_OUTPUT"
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true
          ruby-version: ${{steps.determine-ruby-version.outputs.RUBY_VERSION}}
          working-directory: support/pipeline-visualiser
      - name: Run pipeline visualiser tests
        run: bundle exec rspec
