name: "Review apps: on PR close"
on:
  workflow_call:
    inputs:
      aws-account-number:
        type: string
        default: "842676007477"
      aws-region:
        type: string
        default: "eu-west-2"
      app-name:
        type: string
        description: "The name of the application, used for the ECR repository and CodeBuild project. eg. forms-product-page"

jobs:
  delete-review-app:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-number }}:role/review-github-actions-${{ inputs.app-name }}
          aws-region: ${{ inputs.aws-region }}

      - name: Destroy review app via CodeBuild
        uses: aws-actions/aws-codebuild-run-build@7e46c3fa1c1f217e26a73712796b1f78938b534b # v1.0.19
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          project-name: review-${{ inputs.app-name }}-destroy
          env-vars-for-codebuild: |
            PR_NUMBER
