name: "Lint Workflows"

on:
  workflow_call:

jobs:
  actionlint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Download actionlint
        id: get_actionlint
        run: |
          curl -L "https://github.com/rhysd/actionlint/releases/download/v1.7.10/actionlint_1.7.10_linux_amd64.tar.gz" | tar -xvz actionlint
          chmod +x actionlint
          sudo mv actionlint /usr/local/bin/actionlint
        shell: bash
      - name: Check workflow files
        run: actionlint -color
        shell: bash
